### ISSUE TITLE
`mtslack` command continuously finds available updates

### ISSUE THREAD

**Issue by PSalant726** [mallowigi/mtslack#55] opened 2020-12-28 16:32 UTC
**Describe the bug**
With an update available, executing `sudo mtslack` appears to install the update, but subsequent runs of the command continue to find an available update.

**To Reproduce**
1. Run `sudo mtslack`, when an update is available
2. Observe that the update is found and installed, and the command exits without errors
3. Execute `sudo mtslack` again
4. Observe that the update is found and installed again, and the command exits without errors

**Expected behavior**
After installing an update, the `mtslack` command should not continue to find an available update, and should instead execute as normal.

**Screenshots**
```
$ sudo mtslack
Checking for updates...
A new update is available! Starting autoupdate...
Finished checking for updates!
Update finished. Please rerun the command.

~
$ sudo mtslack
Checking for updates...
A new update is available! Starting autoupdate...
Finished checking for updates!
Update finished. Please rerun the command.

~
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Version 15.0.0
 - 
**Additional context**
As a workaround, you can `npm install -g mtslack` again. For me, this installed v16.0.0. Then, running `sudo mtslack` works as expected.

**Comment by mallowigi** [comment] 2020-12-28 18:18
Thanks for the issue, but I won't look at it. I have plenty of work outside of that, and it looks like you have a workaround. Besides, I couldn't reproduce 👍🏽 

I'm closing it.

**Closed by mallowigi** 2020-12-28 18:18 UTC

**Comment by PSalant726** [comment] 2020-12-28 19:18
Understandable. FWIW - I think the issue is just that the [current `package.json`](https://github.com/mallowigi/mtslack/blob/master/package.json#L3) still has `"version": "15.0.0"`. The `cli-autoupdate` package _is_ correctly updating `mtslack`, but because [the `mtslack` npm package](https://www.npmjs.com/package/mtslack) is currently versioned at `16.0.0`, it gets caught in this loop.
